RELATED: TNT-395 Added support for total labels visibility control
gooddata/gooddata-ui-sdk pull request #2664
Opened 2022-06-21 07:45 UTC by marmil-cz

Added support for independent data/total labels visibility control.

This feature enables to control data labels and total labels independently for bar charts and column chars. Till now there was only one controller for both types of labels.

JIRA: TNT-395

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

2022-06-21 07:45 UTC, marmil-cz commented
extended test

2022-06-21 08:17 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8445/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10303/ : FAILURE in 11m 41s

2022-06-21 08:42 UTC, gdgate commented
Build in pipeline check-extended aborted.

2022-06-21 08:47 UTC, gdgate commented
Build in pipeline check aborted.

2022-06-21 08:47 UTC, marmil-cz commented
extended test

2022-06-21 09:04 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8452/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10309/ : FAILURE in 16m 51s

2022-06-21 09:11 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8453/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1648/ : FAILURE in 23m 32s

2022-06-21 10:45 UTC, marmil-cz commented
extended test

2022-06-21 11:24 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1649/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-21 13:11 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8461/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10322/ : FAILURE in 13m 36s

2022-06-21 13:34 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8463/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1650/ : FAILURE in 24m 40s

2022-06-21 13:51 UTC, marmil-cz commented
extended test

2022-06-21 18:44 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8475/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/229/ : SUCCESS in 11m 43s

2022-06-22 19:47 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8494/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10354/ : SUCCESS in 13m 09s

2022-06-22 20:07 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1655/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-22 20:08 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8495/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1655/ : UNSTABLE in 29m 47s

2022-06-23 06:10 UTC, marmil-cz commented
extended test

2022-06-23 06:22 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8499/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10360/ : SUCCESS in 12m 41s

2022-06-23 06:40 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1656/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-23 06:40 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8500/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1656/ : SUCCESS in 29m 57s

2022-06-23 06:55 UTC, marmil-cz commented
extended check cypress

2022-06-23 07:07 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8501/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/231/ : SUCCESS in 11m 38s

2022-06-23 08:51 UTC, marmil-cz commented
extended test

2022-06-23 09:12 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8504/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10362/ : FAILURE in 21m 17s

2022-06-23 09:23 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1658/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-23 09:24 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8505/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1658/ : UNSTABLE in 32m 20s

2022-06-23 12:56 UTC, marmil-cz commented
extended test

2022-06-23 13:14 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8518/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10378/ : FAILURE in 18m 08s

2022-06-23 13:47 UTC, marmil-cz commented
extended test

2022-06-23 14:23 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1662/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-23 14:24 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8522/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1662/ : UNSTABLE in 36m 05s

2022-06-23 14:55 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8525/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10386/ : FAILURE in 13m 21s

2022-06-24 05:17 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8532/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10392/ : FAILURE in 14m 57s

2022-06-24 05:43 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8533/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10393/ : SUCCESS in 14m 21s

2022-06-24 06:08 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8534/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10394/ : SUCCESS in 14m 32s

2022-06-24 06:50 UTC, marmil-cz commented
extended test

2022-06-24 07:15 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8535/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1664/ : FAILURE in 25m 27s

2022-06-24 07:31 UTC, marmil-cz commented
extended test

2022-06-24 07:57 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8539/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10397/ : FAILURE in 21m 13s

2022-06-24 08:13 UTC, gdgate commented
Build in pipeline check-extended aborted.

2022-06-24 08:15 UTC, marmil-cz commented
extended test

2022-06-24 08:36 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8543/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10402/ : SUCCESS in 22m 23s

2022-06-24 08:51 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8544/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1668/ : UNSTABLE in 35m 17s

2022-06-24 14:26 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8563/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10415/ : FAILURE in 2m 08s

2022-06-24 14:47 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8564/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10417/ : FAILURE in 2m 26s

2022-06-24 14:52 UTC, marmil-cz commented
extended test

2022-06-24 14:54 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8565/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1673/ : FAILURE in 2m 22s

2022-06-26 05:05 UTC, marmil-cz commented
extended test

2022-06-26 05:08 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8566/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1674/ : FAILURE in 2m 37s

2022-06-26 05:23 UTC, marmil-cz commented
extended test

2022-06-26 05:41 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8567/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10418/ : SUCCESS in 19m 03s

2022-06-26 05:49 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1675/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-26 05:50 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8568/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1675/ : SUCCESS in 26m 59s

2022-06-26 20:24 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8569/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10419/ : SUCCESS in 18m 22s

2022-06-27 06:07 UTC, ivan-nejezchleb requested changes

2022-06-27 06:07 UTC, ivan-nejezchleb commented on libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
> +            supportedProperties.controls.dataLabels.totalsVisible = false;
Ok I see now, init value is different for Bar  and Column

2022-06-27 11:21 UTC, marmil-cz commented on libs/sdk-ui-ext/src/internal/components/configurationControls/tests/DataLabelsControl.test.tsx
> +            const expectedNumberOfDropdowns = enableSeparateLabelsFF ? 2 : 1;
Unfortunately it is set manually within test suite. I just wanted to have it ready for the case when we decide to activate the feature flag for all the users on the server and the existing tests will start failing due to new conditions within test cases. Alternatively I could delete those future ready test.

2022-06-27 11:22 UTC, marmil-cz commented on libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
> +            supportedProperties.controls.dataLabels.totalsVisible = false;
yeah, exactly

2022-06-27 11:23 UTC, marmil-cz commented on libs/sdk-model/src/settings/index.ts
> +    enableSeparateLabels?: boolean;
Good point, I will rename it to `enableSeparateTotalLabels`.

2022-06-27 11:35 UTC, ivan-nejezchleb commented on libs/sdk-ui-ext/src/internal/components/configurationControls/tests/DataLabelsControl.test.tsx
> +            const expectedNumberOfDropdowns = enableSeparateLabelsFF ? 2 : 1;
I would keep only currently valid expects and change them once feature enabled, just mention it to  task for change of FF's value

2022-06-27 11:36 UTC, ivan-nejezchleb commented on libs/sdk-ui-charts/api/sdk-ui-charts.api.md
> +export type IDataLabelsTotalsVisible = boolean | string;
I dont expect any extension valid only for total labels and not for normal ones

2022-06-27 11:36 UTC, ivan-nejezchleb commented on libs/sdk-model/src/settings/index.ts
> +    enableSeparateLabels?: boolean;
ok

2022-06-27 13:40 UTC, gdgate commented
Build in pipeline check aborted.

2022-06-27 13:43 UTC, marmil-cz commented
extended test

2022-06-27 13:59 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8587/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10442/ : SUCCESS in 18m 48s

2022-06-27 14:15 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1677/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-27 14:15 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8588/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1677/ : UNSTABLE in 32m 17s

2022-06-27 14:54 UTC, marmil-cz commented
extended test

2022-06-27 15:44 UTC, yenkins commented
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1680/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

2022-06-27 15:44 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8600/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1680/ : SUCCESS in 28m 18s

2022-06-29 05:46 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8636/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10489/ : SUCCESS in 18m 07s

2022-06-29 06:38 UTC, ivan-nejezchleb approved these changes

2022-06-29 06:57 UTC, gdgate commented
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2481/ : SUCCESS in 1m 45s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2777/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1604/ : FAILURE in 17m 25s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10490/ : SUCCESS in 18m 01s

2022-06-29 07:27 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2664

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2022-06-29 07:29 UTC, merged

2022-06-29 07:29 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2482/ : SUCCESS in 1m 15s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2778/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1605/ : SUCCESS in 18m 34s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10491/ : SUCCESS in 20m 37s