Create new Theme via UI
gooddata/gooddata-ui-sdk pull request #2814
Opened 2022-08-03 13:40 UTC by oleg-morozov

JIRA: TNT-925

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

2022-08-03 13:54 UTC, scavnickyj commented on libs/sdk-ui/src/base/localization/bundles/en-US.json
> +        "value": "Paste",
This one might need a comment for the translators as it may have multiple meanings if I'm not mistaken.

2022-08-03 13:58 UTC, scavnickyj commented on libs/sdk-ui-kit/styles/scss/createThemeDialog.scss
> +        background-color: var(--gd-palette-complementary-0, white);
If this var definition already exists as a scss variable, please use it instead of defining it again.

2022-08-03 14:02 UTC, scavnickyj commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx
> +    const providedExamples = !!examples && !!exampleToColorPreview;
What do we expect when an empty array is provided here?

2022-08-03 14:05 UTC, scavnickyj commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialogFooter.tsx
> +                    className={cx("gd-button-link-dimmed", "gd-icon-circle-question")}
No cx needed here

2022-08-03 14:07 UTC, scavnickyj commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingExample.tsx
> +                    className={cx("gd-styling-example-label-action", "s-gd-styling-example-label-action")}
No cx needed here

2022-08-03 14:51 UTC, oleg-morozov commented
extended test

2022-08-03 14:51 UTC, oleg-morozov commented
extended check sonar

2022-08-03 14:51 UTC, oleg-morozov commented
extended check cypress

2022-08-03 14:51 UTC, oleg-morozov commented
extended check plugins

2022-08-03 14:54 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9066/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10902/ : FAILURE in 9m 39s

2022-08-03 15:03 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/28/ : SUCCESS in 11m 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9070/ : SUCCESS in 6s

2022-08-03 15:07 UTC, yenkins commented
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**drilling.spec.ts**|2|-|23.4930s|
|✅|**barChartDrilling.spec.ts**|4|-|11.1590s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|11.4140s|
|✅|**dashboard.spec.ts**|9|-|55.4770s|
|✅|**pivotTableSizing.spec.ts**|1|-|10.1500s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.0350s|
|✅|**attributeFilterConfig.spec.ts**|3|-|31.9490s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.9770s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|11.4920s|
|✅|**dashboardFiltering.spec.ts**|2|-|26.6010s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.5330s|
|✅|**headlineChartDrilling.spec.ts**|2|-|8.4020s|
|✅|**attributeFilterButton.spec.ts**|9|-|37.1140s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|24.7320s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|11.2600s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|20.6670s|
|✅|**dateFilter.spec.ts**|9|-|19.5810s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/266/).

2022-08-03 15:07 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9069/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/266/ : SUCCESS in 15m 46s

2022-08-03 15:07 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-check-extended-sonar-PR2814

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2022-08-03 15:07 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9068/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1711/ : SUCCESS in 16m 00s

2022-08-03 15:15 UTC, gdgate commented
Build in pipeline check-extended aborted.

2022-08-03 15:31 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9071/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10903/ : SUCCESS in 15m 54s

2022-08-03 15:46 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/BubbleHeaderSeparator.tsx
> +    const { title, message } = props;
you can put this directly to the function param
({ title, message }: IBubbleHeaderSeparatorProps)

2022-08-03 15:50 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/ColorPreview.tsx
> +export const ColorPreview = (props: IColorPreviewProps) => {
can this component be used also in StylingPickerListItem.tsx to replace almost the same code?
{colorsPreview.map((color, index) => (
                        <span
                            key={index}
                            className="gd-styling-picker-list-item-color"
                            style={{ backgroundColor: color }}
                        />
                    ))}

2022-08-03 15:53 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx
> +    stylingContent?: IThemeMetadataObject;
replace IThemeMetadataObject type by StylingPickerItem, that will be later extended to 
export type StylingPickerItem = IThemeMetadataObject | IColorPaletteMetadataObject;

and types will not be affected in components

2022-08-03 15:58 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx
> +            setInvalidDefinition(true);
I would rather set this flag on single place in handleDefinitionFieldChange. Now half of cases is treated here and half there

2022-08-03 16:00 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx
> +    const isSubmitDisabled = useMemo(
submit should not be disabled when invalidDefinition is provided?

2022-08-03 16:01 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx
> +                onSubmit={() => (validateDefinition(definitionField) ? onSubmit : undefined)}
dont you want to call onSubmit or change this to 
                onSubmit={validateDefinition(definitionField) ? onSubmit : undefined}
                
?

2022-08-03 16:02 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialogFooter.tsx
> +    onCancel?: (data?: any) => void;
pls try to remove any type. onCancel probably does not require any param and onSubmit should provide whole StylingPickerItem, right?

2022-08-03 16:03 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialogFooter.tsx
> +                    type="button"
is this type needed?

2022-08-03 16:04 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx
> +                                    key={example.id}
are we sure that every example will/need to have ID?

2022-08-03 16:06 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/createThemeDialog.scss
> +// (C) 2022 GoodData Corporation
dont we want to have name of this scss file in sync with component name?

2022-08-03 16:16 UTC, ivan-nejezchleb requested changes
Please check individual comments in code

2022-08-04 11:15 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9078/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10913/ : SUCCESS in 15m 55s

2022-08-04 13:34 UTC, ivan-nejezchleb approved these changes

2022-08-04 13:57 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2814

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2022-08-04 13:57 UTC, merged