PoC run integrated test tiger UI-SDK
gooddata/gooddata-ui-sdk pull request #3340
Opened 2022-12-29 03:54 UTC by maitrieuphilong

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

2022-12-29 04:06 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10900/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12987/ : FAILURE in 11m 26s

2022-12-29 07:32 UTC, caohhung requested changes

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +#!/bin/bash
This file should be 

- moved to `common/scripts/ci` . and file name should be s.t like `run-sdk-backend-tiger-integration-tests-with-live-backend.sh`
- Or moved to `libs/sdk-backend-tiger/scripts` and replace `integrated-test-AIO.sh`

2022-12-29 07:32 UTC, caohhung commented on tools/plugin-toolkit/src/_base/env.ts
> +        dotEnvContent.TEST_EMPTY_WORKSPACE_ID = TEST_EMPTY_WORKSPACE_ID;
Please introduce a nested `if` condition for `WORKSPACE_ID`? do you know why?

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +441851189095.dkr.ecr.eu-central-1.amazonaws.com/nas/data-loader:master /bin/bash -c "/data_load/data_load.py -w goodsales -d pg_local --debug  --skip-download --no-schema-versioning -f"
Best practice - To reduce the complexity + level of arg passing:
```
docker run -it --rm \
  -e DB_PORT=5432 \
 .....

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +  -d '{
Do you think having this body in file is better?

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +  -H "Authorization: Bearer YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz" \
Please set `YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz` as variable in the top of this script, as it's called at least twice

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +# HOST=$(docker inspect "gooddata-cn-ce-manual" | jq -r '.[0].NetworkSettings.IPAddress')
remove comment

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +sleep 120
Replace hard sleep with polling an AIO endpoint

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +docker run --name gooddata-cn-ce-manual -e APP_LOGLEVEL=INFO -e LICENSE_AND_PRIVACY_POLICY_ACCEPTED=YES \
Container name should be unique -> Add `${EXECUTOR_NUMBER}` 
And should be a variables ?

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +docker rm gooddata-cn-ce-manual
Please set them in `trap` in top of script. i.e
```trap "(echo command_1 ; echo command_2) || true" EXIT

Consider to use `docker rm -f` :  `-f, --force     Force the removal of a running container (uses SIGKILL)`

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +  npm run create-ref-workspaces
Problem? `npm run` can be run in jenkins slave.
To use npm/node in jenkins-slave, a node docker images is needed

2022-12-29 07:32 UTC, caohhung commented on run-integrated-tiger.sh
> +docker run --name gooddata-cn-ce-manual -e APP_LOGLEVEL=INFO -e LICENSE_AND_PRIVACY_POLICY_ACCEPTED=YES \
Same for `network`, it should be created with unique name + put into `trap` to be removed later.

`trap`: see comments below

2023-01-02 11:55 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2023-01-03 11:15 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2023-01-03 11:32 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2023-01-04 04:01 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2023-01-04 07:11 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2023-01-04 07:19 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2023-01-04 07:21 UTC, closed without merging