feat: move fast_track to master
gooddata/gooddata-ui-sdk pull request #4914
Opened 2024-04-15 07:13 UTC by hkad98

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

2024-04-15 07:18 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/18709/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20401/ : FAILURE in 1m 14s

2024-04-15 08:32 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/18711/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20405/ : FAILURE in 1m 07s

2024-04-16 07:17 UTC, ivanmjartan commented on examples/playground/src/App.tsx
> -import React, { useMemo } from "react";
remove all changes from playground

2024-04-16 07:18 UTC, ivanmjartan commented on examples/sdk-interactive-examples/scripts/validateExamplesDependencies.mjs
> +import path from "path";
remove all changes from examples

2024-04-16 07:19 UTC, ivanmjartan commented on libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadDashboardAlerts.ts
> +    // SKIPPING THIS FOR FAST TRACK
fix this

2024-04-16 07:21 UTC, ivanmjartan commented on libs/sdk-ui-dashboard/src/model/store/alerts/alertsSelectors.ts
> +    selectAlerts,
nOt sure about this fix SDK only support tiger so no alerts ... if this fix necessary for bear than we need to propagate to different branch

2024-04-16 07:22 UTC, ivanmjartan commented on libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
> +/**
Not sure about this selector ... I guess we have already one defined

2024-04-16 07:22 UTC, ivanmjartan commented on libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
> +const MAX_DRAGGABLE_FILTERS_COUNT = 1_000;
I do not understand this value ?

2024-04-16 07:24 UTC, ivanmjartan commented on libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/InsightWidgetAlert.tsx
> +import React, { useCallback, useMemo, useState } from "react";
Not sure about support alerts and tiger

2024-04-16 07:25 UTC, ivanmjartan commented on libs/sdk-ui-dashboard/styles/scss/fast_track.scss
> +// (C) 2024 GoodData Corporation
rename this css or merge it

2024-04-16 07:27 UTC, ivanmjartan commented on libs/sdk-ui-ext/src/internal/constants/uiConfig.ts
> +export const MAX_METRICS_COUNT = 1_000;
Change const to valid number 1000

2024-04-16 07:30 UTC, ivanmjartan commented on libs/sdk-ui-ext/src/internal/constants/uiConfig.ts
> +export const DEFAULT_PIE_METRICS_COUNT = 1_000;
change all const devinition to validn number not shure about ecma script 2021
Pls change it export const DEFAULT_PIE_METRICS_COUNT = 1000;

2024-04-16 11:15 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2024-04-16 13:30 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/18743/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20430/ : FAILURE in 10m 13s

2024-04-17 06:44 UTC, kandl requested changes

2024-04-17 06:44 UTC, kandl commented on libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
> +    computeKeyDrivers?: (workspaceId: string, metric: IMeasure, sortDirection: "ASC" | "DESC") => Promise<IKeyDriverAnalysis>;
All these method should be likely moved and supported by `sdk-backend-spi`.

2024-10-21 06:48 UTC, closed without merging