RELATED: ONE-4639 Custom styles for Button Component
gooddata/gooddata-ui-sdk pull request #676
Opened 2020-10-02 10:54 UTC by NestorEncinas

Button able to accept different styles

---

Supported PR commands:

| Command         | Description            |
| --------------- | ---------------------- |
| `ok to test`    | Re-run standard checks |
| `extended test` | BackstopJS tests       |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

2020-10-02 10:55 UTC, gdgate commented
Build in pipeline check aborted.

2020-10-02 11:47 UTC, ivan-nejezchleb requested changes

2020-10-02 11:47 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/Button/_variables.scss
> +$button-border-radius-max: calc(max(85px, $gd-button-border-radius));
where is this $gd-button-border-radius defined?

2020-10-02 11:47 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/Button/_variables.scss
> +$button-border-radius: var(--gd-button-border-radius, 3px);
what about units?

2020-10-02 11:47 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/button.scss
> +        border-radius: $button-group-childs-border-radius;
this should not be single variable. It should be here like :
 $button-border-radius 0 0 $button-border-radius

2020-10-02 11:47 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/button.scss
> +        border-radius: $button-group-childs-border-radius;
this should not be single variable. It should be here like :
 0 $button-border-radius $button-border-radius 0

2020-10-02 12:00 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1008/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2594/ : SUCCESS in 20m 24s

2020-10-02 13:52 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1011/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2599/ : SUCCESS in 22m 15s

2020-10-02 13:53 UTC, NestorEncinas commented
extended test

2020-10-02 14:38 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1013/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/374/ : UNSTABLE in 34m 53s

2020-10-05 07:29 UTC, NestorEncinas commented
extended test

2020-10-05 07:54 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1019/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/376/ : UNSTABLE in 24m 58s

2020-10-05 08:00 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/Button/_variables.scss
> +$button-border-radius: var(--gd-button-border-radius, 3px);
will be added in ThemeLoader

2020-10-05 08:30 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1022/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2610/ : SUCCESS in 10m 18s

2020-10-05 08:57 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1024/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2612/ : SUCCESS in 15m 01s

2020-10-05 09:56 UTC, NestorEncinas commented
extended test

2020-10-05 10:28 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1032/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/378/ : SUCCESS in 17m 44s

2020-10-05 12:38 UTC, ivan-nejezchleb approved these changes

2020-10-05 12:50 UTC, merged

2020-10-05 12:50 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/388/ : SUCCESS in 24s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/645/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2622/ : SUCCESS in 11m 45s