Customizable error color
gooddata/gooddata-ui-sdk pull request #787
Opened 2020-11-02 17:27 UTC by strouhaljan

JIRA: ONE-4648

---

Supported PR commands:

| Command         | Description            |
| --------------- | ---------------------- |
| `ok to test`    | Re-run standard checks |
| `extended test` | BackstopJS tests       |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

2020-11-02 17:38 UTC, gdgate commented
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1522/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3098/ : FAILURE in 10m 43s

2020-11-02 20:44 UTC, gdgate commented
Build in pipeline check aborted.

2020-11-02 20:57 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1523/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3100/ : SUCCESS in 11m 01s

2020-11-03 09:37 UTC, strouhaljan commented
extended test

2020-11-03 09:38 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1529/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3105/ : SUCCESS in 10m 53s

2020-11-03 09:56 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1531/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/494/ : SUCCESS in 18m 45s

2020-11-03 12:25 UTC, ivan-nejezchleb requested changes

2020-11-03 12:25 UTC, ivan-nejezchleb commented on libs/sdk-ui-kit/styles/scss/variables.scss
>  $gd-color-negative-dimmed: mix($gd-color-negative, $gd-color-text-light, 10%);
this should be removed and replaced by variable from line 46

2020-11-03 12:25 UTC, ivan-nejezchleb commented on libs/sdk-ui-theme-provider/src/cssProperties.ts
> +        "palette-error-base-mix15-white",
dont you want to keep naming same as for `palette-primary-dimmed50`?

2020-11-03 12:50 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1535/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3111/ : SUCCESS in 10m 45s

2020-11-03 12:56 UTC, ivan-nejezchleb approved these changes

2020-11-03 13:08 UTC, merged

2020-11-03 13:08 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/498/ : SUCCESS in 23s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/758/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3112/ : SUCCESS in 10m 37s