Jsu one 4766
gooddata/gooddata-ui-sdk pull request #806
Opened 2020-11-10 13:35 UTC by strouhaljan

---

Supported PR commands:

| Command         | Description            |
| --------------- | ---------------------- |
| `ok to test`    | Re-run standard checks |
| `extended test` | BackstopJS tests       |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

2020-11-10 13:37 UTC, gdgate commented
Build in pipeline check aborted.

2020-11-10 13:48 UTC, gdgate commented
Build in pipeline check aborted.

2020-11-10 13:48 UTC, gdgate commented
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

2020-11-10 14:03 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1606/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3188/ : SUCCESS in 12m 09s

2020-11-10 14:06 UTC, strouhaljan commented
extended test

2020-11-10 14:21 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1607/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/507/ : UNSTABLE in 15m 15s

2020-11-10 17:27 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1610/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3191/ : SUCCESS in 12m 01s

2020-11-10 17:56 UTC, strouhaljan commented
extended test

2020-11-10 18:11 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1611/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/508/ : UNSTABLE in 15m 17s

2020-11-11 10:39 UTC, strouhaljan commented
extended test

2020-11-11 10:54 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1621/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/510/ : UNSTABLE in 15m 09s

2020-11-11 11:38 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1622/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3204/ : SUCCESS in 12m 30s

2020-11-11 11:41 UTC, strouhaljan commented
extended test

2020-11-11 11:55 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1623/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3205/ : SUCCESS in 13m 59s

2020-11-11 11:57 UTC, gdgate commented
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1624/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/511/ : UNSTABLE in 15m 48s

2020-11-11 12:33 UTC, strouhaljan commented
extended test

2020-11-11 12:50 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1626/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3207/ : SUCCESS in 16m 35s

2020-11-11 12:55 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1627/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/512/ : SUCCESS in 21m 09s

2020-11-11 13:11 UTC, strouhaljan commented
extended test

2020-11-11 13:21 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1628/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3208/ : SUCCESS in 12m 03s

2020-11-11 13:30 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1629/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/513/ : SUCCESS in 18m 53s

2020-11-12 07:45 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1633/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3211/ : SUCCESS in 12m 47s

2020-11-12 10:34 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1637/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3215/ : SUCCESS in 16m 46s

2020-11-12 11:35 UTC, ivan-nejezchleb requested changes

2020-11-12 11:35 UTC, ivan-nejezchleb commented on libs/sdk-ui-tests/stories/visual-regression/kit/themeWrapper.tsx
> +    palette: {
there is tooltip missing, which can be then screenshoted as part of Bubble story

2020-11-12 11:35 UTC, ivan-nejezchleb commented on libs/sdk-ui-tests/stories/visual-regression/kit/themeWrapper.tsx
> +    palette: {
and what about Dialog?

2020-11-12 14:24 UTC, gdgate commented
Build in pipeline check aborted.

2020-11-12 14:25 UTC, strouhaljan commented
extended test

2020-11-12 14:41 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1641/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3220/ : SUCCESS in 16m 11s

2020-11-12 14:46 UTC, gdgate commented
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/1642/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/517/ : SUCCESS in 20m 57s

2020-11-12 15:23 UTC, ivan-nejezchleb approved these changes

2020-11-12 15:41 UTC, merged

2020-11-12 15:41 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/522/ : FAILURE in 3m 58s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/782/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/3222/ : SUCCESS in 13m 39s